import {mount,flushPromises} from '@vue/test-utils'
import {beforeEach,expect,test,vi} from 'vitest'
const api=vi.hoisted(()=>({connections:vi.fn(),proposal:vi.fn(),proposals:vi.fn(),cleanup:vi.fn(),review:vi.fn(),apply:vi.fn(),resolve:vi.fn(),sync:vi.fn(),preview:vi.fn()}))
vi.mock('../../services/memoryGit',()=>({memoryGit:api}))
vi.mock('../../composables/useLocale',()=>({useLocale:()=>({t:(key:string)=>key})}))
const caps={mode:'shadow',can_configure:false,can_preview:true,can_sync:true,can_review:true,can_apply:false,can_resolve:true,can_pull_request:false,external_write_reason:'external_write_disabled'}
const page=()=>({items:[{connectionId:'connection',installationId:'scope-a',repositoryId:'repo',ownerScopeKind:'team',ownerScopeId:'team',provider:'github',providerRepositoryId:'123',targetBranch:'main',rootPath:'knowledge',syncMode:'shadow',writeMode:'off',state:'active',generation:'9007199254740993',capabilities:{...caps},last_success:'2026-09-02T01:00:00Z',current_error:'remote_unconfirmed',cleanup_pending:true,cleanup:[{export_id:'export',old_run_id:'old',cleanup_pending:true,recognized_at:null}],exports:[{export_id:'export',generation:'9007199254740993',base_commit:'a'.repeat(40),created_at:'2026-09-02'}],runs:[{run_id:'run',state:'dead',unfinished:true,eligible:true,reason_code:'remote_unconfirmed'}],proposals:[{proposal_id:'proposal',revision:'9007199254740995',state:'conflicted',export_id:'export'}]}],next_cursor:null})
const detail=()=>({proposal_id:'proposal',connection_id:'connection',export_id:'export',generation:'9007199254740993',revision:'9007199254740995',state:'conflicted',key:{kind:'rule',id:'rule'},head_commit:'b'.repeat(40),proposed_hash:'c'.repeat(64),policy_hash:'d'.repeat(64),current_policy_hash:'d'.repeat(64),expected_asset_revision:'7',expected_inputs:{base:'e'.repeat(64),memory:'f'.repeat(64),git:'a'.repeat(64)},versions:{base:{revision:'1',version_id:'b',path:'rule.yaml',content_hash:'base-hash',source_digest:'source',editable:{statement:'Common original'}},memory:{revision:'7',version_id:'m',path:'rule.yaml',content_hash:'memory-hash',source_digest:'source',editable:{statement:'Current Memory'}},git:{revision:'1',version_id:'g',path:'rule.yaml',content_hash:'git-hash',source_digest:'source',editable:{statement:'Git proposal'}}},conflicts:[{field:'statement',reason:'both_changed'}],gate_reasons:['conflict'],review_reset:true,source:{kind:'git',author_status:'unknown'},capabilities:{...caps}})
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();api.connections.mockResolvedValue(page());api.proposal.mockResolvedValue(detail())})
async function panel(){const module=await import('./MemoryGitPanel.vue').catch(()=>null);expect(module,'Git workbench exists').not.toBeNull();const wrapper=mount(module!.default,{props:{scopeId:'scope-a'}});await flushPromises();return wrapper}
test('shows B/M/G, versions, conflicts, cleanup/current error and server capabilities',async()=>{
  const w=await panel()
  expect(w.text()).toContain('Common original');expect(w.text()).toContain('Current Memory');expect(w.text()).toContain('Git proposal')
  expect(w.text()).toContain('both_changed');expect(w.text()).toContain('remote_unconfirmed');expect(w.text()).toContain('9007199254740995')
  expect(w.get('[data-testid="git-apply"]').attributes('disabled')).toBeDefined()
  expect(w.text()).toContain('external_write_disabled');expect(w.find('[data-testid="git-cleanup"]').exists()).toBe(true)
  api.review.mockResolvedValue({decisionId:'decision'})
  await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
  expect(api.review.mock.calls[0][2]).toMatchObject({expected_generation:'9007199254740993',expected_revision:'9007199254740995',decision:'approve'})
  w.unmount()
})
test('temporary fetch failure retains same-scope result and explicit forbidden clears all bodies',async()=>{
  const w=await panel();api.connections.mockRejectedValueOnce(new Error('network failed'))
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  expect(w.text()).toContain('network failed');expect(w.text()).toContain('Common original')
  api.connections.mockRejectedValueOnce(Object.assign(new Error('access withdrawn'),{status:403,code:'forbidden'}))
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  expect(w.text()).toContain('access withdrawn');expect(w.text()).not.toContain('Common original');expect(w.text()).not.toContain('Git proposal')
  expect(w.get('[data-testid="git-refresh"]').attributes('disabled')).toBeUndefined()
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises();expect(w.text()).toContain('Common original')
  w.unmount()
})
test('scope switch cancels stale requests and immediately removes prior B/M/G',async()=>{
  const w=await panel();let resolve:(v:unknown)=>void=()=>undefined
  api.proposal.mockImplementationOnce(()=>new Promise(r=>{resolve=r}))
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  const oldSignal=api.proposal.mock.calls.at(-1)?.[2]
  api.connections.mockResolvedValueOnce({items:[],next_cursor:null})
  await w.setProps({scopeId:'scope-b'});expect(w.text()).not.toContain('Common original');expect(oldSignal?.aborted).toBe(true)
  resolve(detail());await flushPromises();expect(w.text()).not.toContain('Common original')
  w.unmount()
})
test('review panel displays actual proposed result separately from original B/M/G',async()=>{
  api.proposal.mockResolvedValue({...detail(),proposed_result:{...detail().versions.memory,deleted:true,path:'resolved/path.yaml',content_hash:'actual-result-hash',editable:{statement:'Actual reviewed resolution'}}})
  const w=await panel()
  expect(w.text()).toContain('Actual reviewed resolution');expect(w.text()).toContain('Git proposal')
  expect(w.text()).toContain('resolved/path.yaml');expect(w.text()).toContain('actual-result-hash')
  expect(w.get('[data-testid="git-proposed-result"]').text()).toContain('memory.git.deleted')
  w.unmount()
})
test('lost committed response remains unknown across refresh and connection change, retry keeps exact key and request',async()=>{
  const outcomes=new Map<string,string>(),requests:Array<{scope:string;resource:string;body:unknown;key:string}>=[]
  api.review.mockImplementation(async(scope,resource,body,key)=>{
    requests.push({scope,resource,body:structuredClone(body),key})
    if(!outcomes.has(key)){outcomes.set(key,'decision-one');throw new TypeError('response lost after commit')}
    return {decisionId:outcomes.get(key)}
  })
  const two=page();two.items.push({...two.items[0],connectionId:'other-connection',proposals:[],exports:[]});api.connections.mockResolvedValue(two)
  const w=await panel()
  await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
  expect(w.text()).toContain('memory.git.intent_unknown')
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  expect(w.text()).toContain('memory.git.intent_unknown')
  await w.findAll('.memory-git-connection')[1].trigger('click');await flushPromises()
  expect(w.text()).toContain('memory.git.intent_unknown')
  await w.get('[data-testid="git-retry-intent"]').trigger('click');await flushPromises()
  expect(requests).toHaveLength(2);expect(requests[1]).toEqual(requests[0]);expect(outcomes.size).toBe(1)
  expect(w.text()).not.toContain('memory.git.intent_unknown');w.unmount()
})
test.each(['reject','resolve'] as const)('late %s from cancelled attempt cannot overwrite the same intent retry',async late=>{
  let resolveFirst:(value:unknown)=>void=()=>undefined,rejectFirst:(reason:unknown)=>void=()=>undefined,rejectSecond:(reason:unknown)=>void=()=>undefined
  const first=new Promise((resolve,reject)=>{resolveFirst=resolve;rejectFirst=reject}),second=new Promise((_resolve,reject)=>{rejectSecond=reject})
  api.review.mockImplementationOnce(()=>first).mockImplementationOnce(()=>second)
  const two=page();two.items.push({...two.items[0],connectionId:'other-connection',proposals:[],exports:[]});api.connections.mockResolvedValue(two)
  const w=await panel()
  try {
    await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
    const original=api.review.mock.calls[0],key=original[3]
    await w.findAll('.memory-git-connection')[1].trigger('click');await flushPromises()
    expect(original[4].aborted).toBe(true)
    await w.get('[data-testid="git-retry-intent"]').trigger('click');await flushPromises()
    expect(api.review.mock.calls[1].slice(0,4)).toEqual(original.slice(0,4))
    if(late==='reject')rejectFirst(new TypeError('old response lost'));else resolveFirst({decisionId:'old-response'})
    await flushPromises()
    expect(w.text()).toContain('memory.git.intent_pending')
    expect(w.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeDefined()
    const handled=w.findAll('button').find(b=>b.text()==='memory.git.intent_handled')!
    expect(handled.attributes('disabled')).toBeDefined()
    await handled.trigger('click');expect(w.text()).toContain(key)
    rejectSecond(new TypeError('current response lost'));await flushPromises()
    expect(w.text()).toContain('memory.git.intent_unknown');expect(w.text()).toContain(key)
    expect(JSON.parse(sessionStorage.getItem('memory.git.intents.v1')!)).toMatchObject([{key,state:'unknown'}])
  }finally{rejectSecond(new TypeError('test cleanup'));w.unmount()}
})
test.each(['reject','resolve'] as const)('late %s from an old intent cannot release a different current action',async late=>{
  let resolveFirst:(value:unknown)=>void=()=>undefined,rejectFirst:(reason:unknown)=>void=()=>undefined,rejectSecond:(reason:unknown)=>void=()=>undefined
  const first=new Promise((resolve,reject)=>{resolveFirst=resolve;rejectFirst=reject}),second=new Promise((_resolve,reject)=>{rejectSecond=reject})
  api.review.mockImplementationOnce(()=>first).mockImplementationOnce(()=>second)
  const two=page();two.items.push({...two.items[0],connectionId:'other-connection',proposals:[{proposal_id:'other-proposal',revision:'1',state:'awaiting_review',export_id:'export'}]});api.connections.mockResolvedValue(two)
  api.proposal.mockImplementation(async(_scope,id)=>({...detail(),proposal_id:id,connection_id:id==='other-proposal'?'other-connection':'connection'}))
  const w=await panel()
  try {
    await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
    await w.findAll('.memory-git-connection')[1].trigger('click');await flushPromises()
    await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
    expect(api.review.mock.calls[1][1]).toBe('other-proposal')
    if(late==='reject')rejectFirst(new TypeError('old response lost'));else resolveFirst({decisionId:'old-response'})
    await flushPromises()
    expect(w.get('[data-testid="git-review"]').attributes('disabled')).toBeDefined()
    expect(w.findAll('[data-testid="git-retry-intent"]').every(button=>button.attributes('disabled')!==undefined)).toBe(true)
    expect(w.text()).toContain('memory.git.intent_pending')
    rejectSecond(new TypeError('new response lost'));await flushPromises()
    const markers=JSON.parse(sessionStorage.getItem('memory.git.intents.v1')!)
    expect(markers).toHaveLength(2);expect(markers.every((marker:{state:string})=>marker.state==='unknown')).toBe(true)
  }finally{rejectSecond(new TypeError('test cleanup'));w.unmount()}
})
test('scope change clears pending resolution body, abort is unknown, metadata-only intent cannot auto retry',async()=>{
  api.resolve.mockImplementation(()=>new Promise(()=>undefined))
  const w=await panel(),button=w.findAll('button').find(b=>b.text()==='memory.git.use_git')!
  await button.trigger('click');await flushPromises()
  const signal=api.resolve.mock.calls[0][4]
  api.connections.mockResolvedValueOnce({items:[],next_cursor:null})
  await w.setProps({scopeId:'scope-b'});await flushPromises()
  expect(signal.aborted).toBe(true);expect(w.text()).not.toContain('Git proposal')
  const stored=sessionStorage.getItem('memory.git.intents.v1')!
  expect(stored).toContain('resolve');expect(stored).not.toMatch(/Git proposal|editable|expected_inputs|scope-grant|body/)
  await w.setProps({scopeId:'scope-a'});await flushPromises()
  expect(w.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeDefined()
  expect(w.text()).toContain('memory.git.intent_manual');expect(api.resolve).toHaveBeenCalledTimes(1)
  await w.findAll('button').find(b=>b.text()==='memory.git.use_git')!.trigger('click');await flushPromises()
  expect(api.resolve).toHaveBeenCalledTimes(1)
  w.unmount()
})
test('expired and restored metadata intents require explicit handling and bounded storage never evicts unknown',async()=>{
  const items=Array.from({length:8},(_,i)=>({scope:'scope-a',connection:'connection',resource:`other-${i}`,operation:'review',key:`stable-${i}`,state:'unknown',createdAt:Date.now()-24*60*60*1000}))
  sessionStorage.setItem('memory.git.intents.v1',JSON.stringify(items))
  const w=await panel()
  expect(w.findAll('[data-testid="git-retry-intent"]')).toHaveLength(8)
  expect(w.findAll('[data-testid="git-retry-intent"]').every(b=>b.attributes('disabled')!==undefined)).toBe(true)
  expect(w.text()).toContain('memory.git.intent_manual')
  await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
  expect(api.review).not.toHaveBeenCalled();expect(JSON.parse(sessionStorage.getItem('memory.git.intents.v1')!)).toHaveLength(8)
  expect(w.text()).toContain('memory.git.intent_capacity')
  w.unmount()
})
test('live unknown intent stops retry before server 24h expiry and storage failure retains in-memory exact intent',async()=>{
  vi.stubGlobal('sessionStorage',{getItem:()=>null,setItem:()=>{throw new Error('quota')}})
  api.review.mockRejectedValue(new TypeError('lost'))
  const w=await panel()
  await w.get('[data-testid="git-review"]').trigger('click');await flushPromises()
  expect(w.text()).toContain('memory.git.intent_unknown');expect(w.text()).toContain('memory.git.intent_storage_warning')
  expect(w.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeUndefined()
  const time=vi.spyOn(Date,'now').mockReturnValue(Date.now()+23*60*60*1000+1000)
  await w.get('[data-testid="git-retry-intent"]').trigger('click');await flushPromises()
  expect(api.review).toHaveBeenCalledTimes(1);expect(w.text()).toContain('memory.git.intent_manual')
  time.mockRestore();w.unmount();vi.unstubAllGlobals()
})
test('forbidden refresh scrubs unknown resolution and restoring markers never restores its body',async()=>{
  api.resolve.mockRejectedValue(new TypeError('response lost'))
  const w=await panel()
  await w.findAll('button').find(b=>b.text()==='memory.git.use_git')!.trigger('click');await flushPromises()
  api.connections.mockRejectedValueOnce(Object.assign(new Error('withdrawn'),{status:403,code:'forbidden'}))
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  expect(w.text()).not.toContain('Git proposal');expect(w.text()).toContain('memory.git.intent_unknown')
  expect(w.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeDefined()
  w.unmount()
  const restored=await panel();expect(restored.text()).toContain('memory.git.intent_manual')
  expect(restored.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeDefined()
  expect(api.resolve).toHaveBeenCalledTimes(1);restored.unmount()
})
test('observed generation change clears old result and exact resolution request but preserves its unknown key',async()=>{
  api.resolve.mockRejectedValue(new TypeError('lost'))
  api.proposal.mockResolvedValue({...detail(),proposed_result:{...detail().versions.git,editable:{statement:'Old generation result'}}})
  const w=await panel()
  await w.findAll('button').find(b=>b.text()==='memory.git.use_git')!.trigger('click');await flushPromises()
  const key=api.resolve.mock.calls[0][3],changed=page();changed.items[0].generation='9007199254740994'
  api.connections.mockResolvedValueOnce(changed);api.proposal.mockImplementationOnce(()=>new Promise(()=>undefined))
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  expect(w.text()).not.toContain('Old generation result');expect(w.text()).not.toContain('Git proposal')
  expect(w.get('[data-testid="git-retry-intent"]').attributes('disabled')).toBeDefined()
  expect(w.text()).toContain(key);expect(w.text()).toContain('memory.git.intent_unknown')
  expect(api.resolve).toHaveBeenCalledTimes(1);w.unmount()
})
test('proposal and cleanup continuation use independent cursors and expose page-outside pending',async()=>{
  const value=page();Object.assign(value.items[0],{proposals_next_cursor:'proposal-cursor',proposal_total:21,cleanup_next_cursor:'cleanup-cursor',cleanup_total:51,cleanup_pending_count:1})
  api.connections.mockResolvedValue(value)
  api.proposals.mockResolvedValue({connection_id:'connection',generation:value.items[0].generation,items:[{proposal_id:'next-proposal',revision:'2',state:'pending-page-two',export_id:'export'}],total:21,next_cursor:null})
  api.cleanup.mockResolvedValue({connection_id:'connection',generation:value.items[0].generation,items:[{export_id:'cleanup-page-two',cleanup_pending:true,recognized_at:null}],total:51,pending_count:1,cleanup_pending:true,next_cursor:null})
  const w=await panel()
  await w.get('[data-testid="git-proposals-next"]').trigger('click');await flushPromises()
  expect(api.proposals.mock.calls[0].slice(0,3)).toEqual(['scope-a','connection','proposal-cursor']);expect(w.text()).toContain('pending-page-two')
  await w.get('[data-testid="git-cleanup-next"]').trigger('click');await flushPromises()
  expect(api.cleanup.mock.calls[0].slice(0,3)).toEqual(['scope-a','connection','cleanup-cursor']);expect(w.text()).toContain('cleanup-page-two')
  expect(w.find('[data-testid="git-proposals-first"]').exists()).toBe(true);w.unmount()
})
test.each(['proposals','cleanup'] as const)('returning A-last to B to A restores %s first-page navigation',async kind=>{
  const value=page();Object.assign(value.items[0],{proposals_next_cursor:'p-next',cleanup_next_cursor:'c-next',proposal_total:21,cleanup_total:21})
  value.items.push({...value.items[0],connectionId:'connection-b',proposals:[],cleanup:[]})
  api.connections.mockResolvedValue(value)
  const first=kind==='proposals'?[{proposal_id:'p-first',revision:'1',state:'first-page-proposal',export_id:'export'}]:[{export_id:'first-page-cleanup',cleanup_pending:true,recognized_at:null}]
  const last=kind==='proposals'?[{proposal_id:'p-last',revision:'1',state:'last-page-proposal',export_id:'export'}]:[{export_id:'last-page-cleanup',cleanup_pending:true,recognized_at:null}]
  api[kind].mockImplementation(async(_scope,_connection,cursor)=>({connection_id:'connection',generation:value.items[0].generation,
    items:cursor?last:first,total:21,pending_count:21,cleanup_pending:true,next_cursor:cursor?null:'next'}))
  const w=await panel()
  await w.get(`[data-testid="git-${kind}-next"]`).trigger('click');await flushPromises()
  expect(w.text()).toContain(kind==='proposals'?'last-page-proposal':'last-page-cleanup')
  await w.findAll('.memory-git-connection')[1].trigger('click');await flushPromises()
  await w.findAll('.memory-git-connection')[0].trigger('click');await flushPromises()
  expect(w.find(`[data-testid="git-${kind}-first"]`).exists()).toBe(true)
  await w.get(`[data-testid="git-${kind}-first"]`).trigger('click');await flushPromises()
  expect(w.text()).toContain(kind==='proposals'?'first-page-proposal':'first-page-cleanup')
  expect(w.find(`[data-testid="git-${kind}-first"]`).exists()).toBe(false)
  w.unmount()
})
test('child page is aborted and stale content discarded after connection or generation changes',async()=>{
  const value=page();Object.assign(value.items[0],{cleanup_next_cursor:'cursor',cleanup_total:51});value.items.push({...value.items[0],connectionId:'other-connection',cleanup:[],cleanup_pending:false,proposals:[]})
  api.connections.mockResolvedValue(value)
  let resolve:(v:unknown)=>void=()=>undefined
  api.cleanup.mockImplementation(()=>new Promise(r=>{resolve=r}))
  const w=await panel()
  await w.get('[data-testid="git-cleanup-next"]').trigger('click');await flushPromises()
  const signal=api.cleanup.mock.calls[0][3]
  await w.findAll('.memory-git-connection')[1].trigger('click');await flushPromises()
  resolve({connection_id:'connection',generation:value.items[0].generation,items:[{export_id:'stale-cleanup-secret'}],next_cursor:null});await flushPromises()
  expect(signal.aborted).toBe(true);expect(w.text()).not.toContain('stale-cleanup-secret')
  await w.findAll('.memory-git-connection')[0].trigger('click');await flushPromises()
  await w.get('[data-testid="git-cleanup-next"]').trigger('click');await flushPromises()
  const changed=page();changed.items[0].generation='9007199254740994';api.connections.mockResolvedValueOnce(changed)
  await w.get('[data-testid="git-refresh"]').trigger('click');await flushPromises()
  resolve({connection_id:'connection',generation:value.items[0].generation,items:[{export_id:'stale-generation-secret'}],next_cursor:null});await flushPromises()
  expect(w.text()).not.toContain('stale-generation-secret');w.unmount()
})
