package sessiondocument

import (
	"os"
	"path/filepath"
	"testing"
)

func TestRequestedSnapshotCapturesScriptGeneratedDocument(t *testing.T) {
	root := t.TempDir()
	file := filepath.Join(root, "report.html")
	if err := os.WriteFile(file, []byte("<h1>Generated by Python</h1>"), 0600); err != nil {
		t.Fatal(err)
	}
	result := CaptureRequestedDocument(root, "session", "request", file, 1024)
	if result.Reason != "" || string(result.Bytes) != "<h1>Generated by Python</h1>" || result.DocumentID == "" || result.VersionID == "" {
		t.Fatalf("capture failed: %#v", result)
	}
	relative := CaptureRequestedDocument(root, "session", "request-2", "report.html", 1024)
	if result.DocumentID != relative.DocumentID {
		t.Fatal("absolute and relative links must identify the same document")
	}
	if result.SourceTurnID != "document-request:request" {
		t.Fatal("must not pretend a user-requested snapshot is an agent file change")
	}
}

func TestRequestedSnapshotRejectsUnsafeAndUnsupportedPaths(t *testing.T) {
	root, outside := t.TempDir(), t.TempDir()
	file := filepath.Join(outside, "secret.html")
	if err := os.WriteFile(file, []byte("secret"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(file, filepath.Join(root, "link.html")); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "large.html"), make([]byte, 2048), 0600); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{file, "../secret.html", "link.html", ".env", "https://example.com/a.html", "file:///etc/a.html", "large.html", "missing.html"} {
		result := CaptureRequestedDocument(root, "session", "request", path, 1024)
		if result.Reason == "" || len(result.Bytes) != 0 {
			t.Errorf("unexpectedly read %q", path)
		}
	}
	for _, values := range [][3]string{{"", "session", "request"}, {root, "", "request"}, {root, "session", ""}} {
		if CaptureRequestedDocument(values[0], values[1], values[2], "report.html", 1024).Reason == "" {
			t.Fatal("missing authority accepted")
		}
	}
}
