import Foundation

private func expect(_ condition: @autoclosure () -> Bool, _ message: String) { if !condition() { fputs("FAIL: \(message)\n", stderr); exit(1) } }
let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let view = try String(contentsOf: root.appendingPathComponent("ios/Pocketctl/Views/SessionDetailView.swift"), encoding: .utf8)
let vm = try String(contentsOf: root.appendingPathComponent("ios/Pocketctl/ViewModels/SessionDetailViewModel.swift"), encoding: .utf8)
expect(view.contains("composerToolbar(vm: vm)"), "composer must use a second toolbar row")
expect(view.contains("lineLimit(2...6)"), "composer must grow from two to six lines")
expect(view.contains("frame(width: 32, height: 32)"), "visible send button should be compact")
expect(view.contains("contentShape(Rectangle())"), "compact send button must retain an accessible hit target")
expect(!view.contains("// Model pill — reflects terminal"), "navigation model pill must be removed")
expect(vm.contains("pendingPermission"), "permission changes must track pending state")
expect(vm.contains("permissionConfigChanged"), "daemon confirmation must be authoritative")
expect(vm.contains("permissionMutable && !isExecuting"), "permission editing must follow authoritative running/busy status like web")
expect(!vm.contains("permissionMutable && !isWorking"), "optimistic awaiting-start state must not permanently disable permission editing")
expect(view.contains(".popover(isPresented: $showPermissionPanel)"), "permission selector must use a visible button-anchored popover")
expect(!view.contains("if showPermissionPanel { permissionPanel(vm: vm).offset(y: -52) }"), "permission selector must not escape the safe-area inset through an offset overlay")
expect(!view.contains(".disabled(!vm.canChangePermission)"), "permission button must remain tappable so disabled reasons are visible")
expect(vm.contains("permissionChangeUnavailableReason"), "view model must explain why permission changes are unavailable")
expect(view.contains("showPermissionPanel = true"), "permission button must open rather than toggle the selector")
expect(view.contains(".buttonStyle(.plain)"), "permission button needs a stable plain button style")
expect(view.contains(".simultaneousGesture(TapGesture()"), "tapping the message area must dismiss the keyboard")
expect(view.contains(".safeAreaInset(edge: .bottom, spacing: -PCSpacing.md)"), "composer should sit close to the bottom rounded safe-area edge")
expect(view.contains(".padding(.top, PCSpacing.xs)"), "composer should keep only a compact top separation")
expect(view.contains(".padding(.bottom, 0)"), "composer should not add bottom space above the safe-area edge")
expect(!view.contains("ToolbarItemGroup(placement: .keyboard)"), "keyboard toolbar dismiss button must be removed")
expect(view.contains(".swipeToPop {"), "back swipe must first consider keyboard state")
print("SessionComposerRegressionTests passed")
